### ISSUE TITLE
Split creation and connection of entities to simplify api

### ISSUE THREAD

**Issue by zubrailx** [IoT-MHWS/hs-server#18]
For example:

```
req-1) CREATE picture

req-2) CREATE gallery

req-2) CREATE picture_gallery CONNECTION OF picture_id AND gallery_id.
```

Instead of:

```
req-1) CREATE gallery

req-2) CREATE picture CONNECTING TO gallery_id
```

**Comment by niqzart** [comment]
Following ReST:
/galleries/{galleryId}/paintings/ — collection of paintings, connected to gallery {galleryId}
/galleries/{galleryId}/paintings/{paintingId} — specific link from gallery {galleryId} to painting {paintingId} 

Methods:
POST /galleries/{galleryId}/paintings/ — create a new link (can return 409 if exists)
GET /galleries/{galleryId}/paintings/ — list existing links
PUT /galleries/{galleryId}/paintings/{paintingId} — create link or edit metadata of an existing link
DELETE /galleries/{galleryId}/paintings/{paintingId} — delete a link
